describe('User management', () => {
 
    it('Admin can search for a user', function () {
        cy.get('.ant-menu-submenu-title .anticon')
        .click()
        cy.get('.ant-menu-inline .ant-menu-submenu-title')
        .eq(2)
        cy.contains('Users')
        .click()
       cy.get('.ant-menu-item a[href="/admin/users"]')
        .click()
        cy.get('.ant-input-affix-wrapper').type('allay_allan')
 
    })
    it('User can edit a user details', function () {
        // cy.get('ant-table-cell a[href="/admin/users/edit/c1d36d9a-b771-410b-959e-af2c04d132a2"]')
        // cy.get('.ant-table-cell')
            cy.contains('Edit')
            .click()
            // cy.get('#firstName').type('New')
    })

    it('Admin can add a user', function () {
        cy.get('.ant-space-item .create-user')
            .click()
        cy.get('input#firstName')
            .type('QA')
        cy.get('input#lastName')
            .type('tester')
        cy.get('input#email')
            .type('tester@gmail.com')
        cy.get('input#username')
            .type('tester')
        cy.get('.ant-select-selector')
            // .eq(1)
        // cy.contains('label', 'Admin')
        //     .click()
        // cy.get('.rc-virtual-list-holder-inner div[title="Update Password"]')
        //     .should('have.text', 'Update Password')
        //     cy.get('.ant-select-selector')
        //     .eq(1)
        //     .click()
        // cy.get('.rc-virtual-list-holder-inner div[title="Testers"]')
        //     .should('have.text', 'Testers')
        //     .click()
        // cy.get('.ant-form-item-control-input button[type="submit"]')
            .click()
            cy.get('.ant-select-item-option-content')
            cy.contains('SK') .click()
            cy.contains('Save').click()
            cy.get('#password').type('123')

    })

    // it('User can move to the next page of the users list', function () {
    //     cy.get('.ant-pagination .ant-pagination-next')
    //         .click()
    // })

    // it('User can view more than 5 users per page', function () {
    //     cy.get('.ant-pagination-options .ant-select-selector')
    //         .click()
    //     cy.get('.rc-virtual-list-holder-inner div[title="10 / page"]')
    //         .click()
    //     cy.get('.ant-pagination-options .ant-select-selector')
    //         .click()
    //     cy.get('.rc-virtual-list-holder-inner div[title="20 / page"]')
    //         .click()
    // })
})